export const INVITE_STATUS = {
  PENDING: "PENDING",
  ACCEPTED: "ACCEPTED",
  DECLINED: "DECLINED",
  EXPIRED: "EXPIRED",
  CANCELLED: "CANCELLED",
};

export const INVITE_TYPE = {
  DIRECT: "DIRECT",
  AUTO: "AUTO",
};

export const TERMINAL_INVITE_STATUSES = [
  INVITE_STATUS.ACCEPTED,
  INVITE_STATUS.DECLINED,
  INVITE_STATUS.EXPIRED,
  INVITE_STATUS.CANCELLED,
];
