export const REQUEST_STATUS = {
  OPEN: "OPEN",
  MATCHING: "MATCHING",
  PARTIAL: "PARTIAL",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
  EXPIRED: "EXPIRED",
};

export const TERMINAL_REQUEST_STATUSES = [
  REQUEST_STATUS.COMPLETED,
  REQUEST_STATUS.CANCELLED,
  REQUEST_STATUS.EXPIRED,
];
